/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package one.life;

import one.life.view.*;

public class App {
	public static void main(String[] args) {
		System.out.print("Program running");
		View.gui();
	}
}
