/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

public class App {
	public static void main(String[] args) {
		// @TODO
		System.out.print("Server Running");
	}
}
